import sys
import os
import subprocess
import logging
import convert_moves
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
# import kociemba.search

# these results were produced by original Kociemba's Java implementation
javares = [
    ("BBURUDBFUFFFRRFUUFLULUFUDLRRDBBDBDBLUDDFLLRRBRLLLBRDDF",
    "B U' L' D' R' D' L2 D' L F' L' D F2 R2 U R2 B2 U2 L2 F2 D' ",
    "B X BP LP FP RP FP LD FP L X BP LPY R BDX FD L FDX BD LDY LD FDX FP "),

    ("FDLUUURLFLBDFRRDLBBBUBFLDDLFBBUDUBRLURDFLRUFRFLRFBDUDR",
    "U F' L2 U F' L2 F L2 F2 D L' F' U2 B2 D F2 D' R2 L2 D F2 U' ",
    "X B X BP LDY L BPX BDX FX FDX BD RY RP BPX BDX BDX B X BDX FP RDLD FX FDX FP "),

    ("UDRFULDRBLDUBRDUFBFBDRFDFURLBBLDRDURLLRULUFBUFRBFBFDLL",
    "F U2 D2 L' F2 D' B R L2 U F U F2 D2 B2 D R2 U2 F2 L2 B2 ",
    "FX BDFD LPY RD FP L X BDFX F R F RD BD LD B X BDX BD RDY RDY RD "),

    ("LRLLURRLBDUULRFUFLFDRUFBRBLDUFDDRRBDDFURLLBFFBDBUBBFDU",
    "B2 D' R2 F U R F' D2 L' B D F2 R2 L2 U' B2 D2 B2 U B2 ",
    "BDX FP RDY R B X F RP X BDX FP L X F RDY RDLD BPX BDX BDX FDX B X BD "),

    ("UUULULFLFDUBDRRDBBUFLFFLBRRLDFFDDBUUFBRRLDRUDLBLFBBRRD",
    "U2 F' D F U F' U F2 R' F R' D2 R2 F2 U2 D B2 U2 L2 F2 ",
    "X BDX BPX B X FX B X BPX FX FD RP F RP X FD RDY RD BDF LD BDX BD RD "),

    ("LRRFUUBDLFBBLRDLLRUFDLFURLFBBUBDDDDUDULRLFRRDUUBRBFFBF",
    "R' B' D' R' B' L F2 U' D F' R2 L2 U' R2 F2 U R2 U B2 D' ",
    "RP BPX FP RP X FP L BDX BFP X FP RDLDY RP X FDX BD RY RDY L FD RP "),

    ("FBRDULFBRFBBRRRDLBRRUDFUUDFLBLFDUBFDLLDLLFRRBUUUDBFLUD",
    "U F R' D' R' U2 L D B' R L' U' B2 L2 U2 D2 B2 R2 D L2 B2 ",
    "X B X B RP X BP RP FD L B X BP RLPY RP BDX BD RDLDY LD FDX B X FD LD "),

    ("FLBUULFFLFDURRDBUBUUDDFFBRDDBLRDRFLLRLRULFUDRRBDBBBUFL",
    "U2 D B' U2 R' D2 L2 D R2 L B' U' L2 D L2 D F2 L2 B2 U' ",
    "X BDFX FP X FD RP BD LD B RDL X BPX BP LD F LD FX BD LD FDX FP "),

    ("UBLLURBDLDDFRRLRFLDFBLFURFFFLDBDULBUBDRRLBDDUUURUBFBRF",
    "U' R2 F U2 R' L' F' L U D' R' U' R2 B2 L2 B2 L2 U2 R2 D' F2 ",
    "X BP RDY R BDX BPFP RP B X BPFX BPX BPX FD LD BD LD BDX FDX BDX FP RD "),

    ("UDLFUBLRFRDDLRFDBDBBDDFUUUBFRRLDUFFLBLUFLRRBLFLRUBDBRU",
    "U R' L F L' U' F' D R F' L' B2 U L2 B2 D L2 U2 R2 B2 D ",
    "X B RPL X B LPY LP BP RY L BP RP FDX B RDY RD FX FDX FDX FD RDY L "),

    ("URBLUBDDBURDLRDLDBFBLLFFULDBBFUDFLRRRURBLDFFRLUFRBUDFU",
    "U2 R2 F' R B' D2 B L' B U' R2 B L2 F2 U2 F2 U' R2 D' L2 D R2 ",
    "X BD RDY RP X F LPY RDY R BP RY RP FDX FX FDX FD RD FD RP X FD LP BD L FD "),

    ("BLBDUULUDBLRDRFLBUUBLRFFURDLDFRDRRUFRBFLLUFFBDDULBBRFD",
    "U2 D2 B' D' F B L2 F2 L D2 L' U F2 U L2 D L2 U2 L2 D F2 ",
    "X BDFDX FP X BPX BF LD FD L X FD LP B X BDX F LD B LD FD LD B X FD "),

    ("ULFUUURRURLLLRRUBLDFFLFFBDRURBRDDDFBFBFFLDBBLDBLUBDDUR",
    "U2 B2 L2 B' D R U2 B2 L' U D2 F' U F2 L2 U2 D' R2 F2 U2 D' F2 ",
    "X BDX FD LD FP X B R FDX BD LPY RLD FP R FDX BD RDLP FDX BD RDLP BD "),

    ("LUFBUUUDDLLRDRRDDLBFFFFRUDBLLRRDBRBFDURFLRFUBUFBBBLULD",
    "D' L B2 U' F' B U B' R2 D2 R' B2 L2 U R2 U B2 R2 U' F2 D2 ",
    "X FP L X FDX FP X BFP X B X FP RDY RDY LP FD RDY RY RDY L FDX FD LPY LDY LD "),

    ("UDDBURDDBUFLFRLFDFRRLRFLUBRFDUBDFRFLBLBRLUFULBLRUBBDUD",
    "U2 B' U' B' R' F2 U' L' F' D B U F2 D2 F2 D F2 R2 U2 F2 D' ",
    "X BDX FP X FP X BP RP FDX BP LPY RP F L B RD FD RD F RDY LD BDX FDX BP "),

    ("UUBUUBUDBDRLFRFDUDBBRBFRFBRUUFDDLLDFFRRDLLBRRUFLLBFLLD",
    "U2 R' B2 U' F2 D B R F2 R U2 B2 U2 R2 U' F2 U2 R2 D' ",
    "X BD RP X FDX FP X FDX FX F R BD RY LD FD LDY LDY RP BD RDY RDY RP "),

    ("BDLRULLRRDFFBRLDRLBFFFFUUDBBRRLDURDDLBULLUUBRUBDUBDFFF",
    "F2 D' L2 U B' D B L F' B U' L2 D2 L2 B2 U R2 F2 U F2 ",
    "FDX FP LD B X FP X B X B L BFP X BP LD FD LDY LD B X FD RDY L X FD "),

    ("LFRUULBBDBFBDRBLFRDDLLFLFRDRBFDDUBUUURRFLBLRDURFUBDFLU",
    "R' D' F' R U' L2 D2 R D L' D' F2 D' R2 U' R2 F2 B2 L2 U2 ",
    "RP X FP X BP RY LPY RDY LDY RY RY RP X FP X FDX BP LD FP LDY RDLDY LD FD "),

    ("UBBRUDBLFRBRRRUFBBLFDDFFFULUFDDDLBLUFUDBLRLFRDULLBRRDU",
    "R' U B R U' R D' R2 L' F' R' F2 R2 U L2 D' B2 U2 L2 D' ",
    "RP X B X F RY LPY L X FP RPLD X FP LP FD LDY L X FD RP X FD LDY RDY LP "),

    ("FRRUUFURDBLFRRFFLUBDLRFBLFUFULLDDBBBULRDLURBDDFRDBBLUD",
    "U R2 U F R' B' R F2 D F' L' D' R2 D B2 D' L2 B2 D R2 L2 ",
    "X B RD B X B RP FP R BDX B X FP LPY LPY LDY R BD RP X FDX FD RY RDLD "),

    ("ULDFUBBRRBDLFRBFFLUUDBFLRFDUDRLDUFUDRRLDLUUDBBBFRBRFLL",
    "F' B' L' U D B U2 F' B' D2 R' B2 U L2 D' F2 R2 D2 R2 U R2 ",
    "BPFP LPY RL B RD BPFP LDY LP BDX F RD BPX BD LDY LDY RDY L X FD "),

    ("ULLLURFBBDUBBRUBLFURRDFDRFUDRRFDBUULLURRLLLDFDFBBBDDFF",
    "U' F2 D2 B2 R2 U B R B U L' B' U B2 D B2 R2 D L2 U D2 ",
    "X BPX BDX BDX BD RDY R B X FX F RY LP FP X FX BDX FX FD RDY RY RDY RLD "),

    ("BDBDURFFRDFDRRLUBLLLFBFURFBBULDDURLDRFURLRUBDLLUUBDFBF",
    "U2 B2 U' F' D' R2 U F2 D' L' B R2 B2 U' B2 U' B2 D' B2 R2 U' ",
    "X BDX FDX FP X FP X FP RD B X BDX BP LPY RY LDY LD FP LD FP LD BP LDY RD FP "),

    ("DRUUUDDBRULLBRBFFLLLBFFDBURLFUUDLRRURRFFLDFLDFDBUBRBBD",
    "D F R L B2 L' B U F' D' R U B2 U F2 U B2 U2 F2 U' L2 ",
    "X FX B RL FD LP FX FX FP X FP R B X FDX FX FDX B X FDX FDX FDX BP LD "),

    ("BDLLURUFRDBDRRRDFURLFLFUBFLRDBLDUBBLDDFFLBLUUFBRDBRFUU",
    "L' D R' U' B D F D F2 B' R B2 U' L2 U' F2 U D F2 R2 D2 ",
    "LPY L X FP RP X F L B L BDFP X B X BD RP X BD RP X BD RL BDX BD LD "),

    ("RRRUURUUBDDBFRBFLURLRFFRLULDBDLDBLLLDFFULDUDBUBFDBRFFB",
    "U D2 R' F' R' U' B R' U' L F2 B2 U2 B2 D' F2 D R2 F2 D2 ",
    "X BFD RP X BP RP X FP X B RP X BP L X BDFDX FDX BDX FP X BDX B RDY LD BD "),

    ("LFRLUUBBLBFUDRRUUFDDUDFFULLBUFLDBLFDFDRBLRBBRFRDUBRRLD",
    "F2 R U' F D2 B D B' L U2 R U F2 U2 R2 U2 R2 U' B2 D' ",
    "FD RY RP F LD B L BPX B RD F RY RDY LD FD LD FD LPY RDY LP "),

    ("FRRBUBDDURLBDRDLUDRLFLFBLBFDUUFDRLUFRRBRLFUUBUDDFBFLLB",
    "U2 D F' B' R' D' L B' R B R L2 D2 L2 F2 U B2 R2 B2 D2 F2 ",
    "X BDFX BPFP RP X BP L X BP R B RLDY LDY RD FDX FX FD LD FDX FDX FD "),

    ("DBUFUFDFUBLLLRURUBLRRDFBFLDUUBFDRDDLFUFBLLLDRFDRBBRURB",
    "F' B' U' B2 D' F L U' B R' D2 L2 U2 F2 D B2 U' F2 U2 L2 ",
    "BPFP X BPX FDX BPX F L X BPX F RP X BD LD FDX FDX FX FDX FP X FDX BD LD "),

    ("BFRFUBBLBLRFDRBDUUUBDFFRLFFULLDDRFDRDULLLRRLFDDRUBUBBU",
    "L F2 R F' U2 R F' L F R U F2 D2 R2 U R2 L2 B2 D2 F2 ",
    "L FD R FP X BD RY RP X B R FX F RD BDX BDX B X BDFD LDY RDY LD "),

    ("BFDDURFBRDBLURLBUUDLFRFBDRURURLDLFFFUBLFLDUFBBRLDBDRUL",
    "L2 U R2 B L' F L' F' R' L F R2 U2 R2 U F2 U F2 D R2 D2 ",
    "LDY RY LD B RP F RP FP RLP F LDY LDY RDY R FD R FD L X FD LD "),

    ("LRBUULRDRDBLLRBDDUFRFDFURLLBFBUDBBFLFBUDLFURDUFDRBLFUR",
    "R' B' D' R2 L B' L D L' B' U2 L2 D2 R2 B2 U' L2 D' F2 B2 ",
    "RP BPX FP RDL X FP L X B LPY RP FDX BDX FDX BD RDY LP FD RP X BDFD "),

    ("RBBDUBBRRFLDFRFFRRDUUFFUDFULLLLDBBLBDBRDLRLUFLUFDBRUDU",
    "U2 F2 U' D2 F U' R B' U L F B2 U D B2 R2 U2 B2 D' F2 ",
    "X BDX BDX BDFP X FX BP RY LP B X B RLDY RL X BDX BD LDY LDY LPY LD "),

    ("FRBUURUDBLBRDRLDFDRBDDFLUFFLULDDLBLRLBFFLRUFBDUUUBRFBR",
    "D B' U' D' F' U2 F' R F D2 F B2 U D2 F2 R2 D2 L2 F2 D' B2 ",
    "X FX FP X BPFP X FP X BDX BP R B X BDX BDFX BFD X BD RDY RDY RD BDX FP X BD "),

    ("FLURURDBRBDBBRUUUUFLDFFULUFFLRDDRLBRLFRFLLBBDLDUFBDBRD",
    "F' U' F2 D2 F2 L' B' R2 U' R F U B2 D L2 D' F2 R2 D L2 U2 ",
    "FP X BPX BDX BDX FD LP BP RDY RP X FX B R FD L X FD LPY LD BDX B X BDX BD "),

    ("BULRUULFRDBDDRLUDRULFFFBLUBDRLFDLURBDBFLLDFRBFFRUBBUDR",
    "U' F2 R' D2 L2 U2 F' B' R' F' B2 U2 D L2 F2 L2 D' F2 U2 F2 ",
    "X BPX BD RP X BD LD FDX BPFP RP BDFP X BDF LDY RDY RD FP X FDX FDX BD "),

    ("FFRRULFBDRFBURLFBUDLBRFFDBRBUUDDDLRLRULRLDULLUDDUBFFBB",
    "U F D' B' U D' F L2 U R F' R2 F2 U' R2 F2 D' R2 U D' B2 ",
    "X B X B X BPX BPX BFP X B LDY L X FX FP X BDX BD LPY LD BDX FP LD BFP X BD "),

    ("DUFBUDBRDBRUFRURRBDFLLFDDLBLFULDURBLFDRDLBUUFLBRFBLURF",
    "U L2 B D' L' U B' R2 L2 D' R F2 B2 R2 U2 B2 U' D2 F2 B2 R2 ",
    "X B LDY L FP X BPX F LPY RDLD BP RY RDLDY LD FDX FDX BPFDX BDFD LD "),

    ("DRRUURBRURUBDRLUBFDBFBFBLFLDRFFDULLDLFRDLLUDBUDFUBLRFB",
    "F2 B D2 R B' U2 B2 D2 F' L B2 R2 F2 L2 U' L2 U' R2 B2 U ",
    "BFD X FD RY LP BD LD FD RP X B LD FD RD BDX FP X FDX BPX FD LDY L "),

    ("BRLFUDLDRFLUFRUFFLFBURFRUUDFBRUDDRRBRLDLLBDLLBUUFBBDDB",
    "F2 D L F' B' L' F2 D F' U' R U F2 L2 F2 L2 F2 U2 L2 U' R2 ",
    "FDX F L X BPFP LP BDX B X FP X BP R B X BD LD BD LD BDX FD LD FP RD "),

    ("UULFUFDLRFDBBRDBLFLFULFUDDURBRRDDURDFUFLLBBFBDRLRBURBL",
    "F' R U B2 D B U2 R' L' F' L' D' F2 R2 U F2 L2 U2 B2 U B2 ",
    "FP RY R BD L B RDY RPLP FP RP X BPX BD LDY R BDX FD RDY RDY L X FD "),

    ("DUDUUUDBUFRFRRBRDUBLLUFDUBFBDDFDLUFFRBLFLFBRRLLBRBDRLL",
    "B2 L U B' R' F2 B D2 R2 U2 R' U' R2 D' R2 D' R2 U B2 U' R2 ",
    "BD L X B X FP RP BDFX BD RD FD RP FP RD BP RD BP RD FX BDX BP RD "),

    ("LDRLUDRLFURBRRRRDDBBRFFUUBFLUDUDLLBFUFDFLUBLBUBFFBDLRD",
    "D F2 R' L2 D' B2 R' D' L B U' F2 R2 B2 R2 F2 U B2 U D ",
    "X FX BD RPLD X BPX BD RP X FP L X FX FP X FD RD BD RD FDX B X FDX BF "),

    ("FUBUUFLBLURRDRFFUDDUFBFRUBDBLRRDLBFFURBLLDLBRDFRLBDLDU",
    "F R' U L B' U' R2 L F D' F' D L2 D B2 U' B2 U2 R2 B2 L2 ",
    "F RP X B L X FP X FP RDL X FX FP X BPX B LD B X BDX BPX FDX FD RDY RDY RD "),

    ("DFRBURUDDLBDRRFUDULLFLFUULFFBRRDRFBRBDBFLUDFLBULDBLBUR",
    "U F2 R B' U L' U2 L' U' B2 L F U' R2 D2 F2 R2 D2 B2 D B2 U' ",
    "X B X BD R FP X F LP FD LP FP X BD L FX BP RD FDX BD RDY RD FD R FD LP "),

    ("RLRUURDLFUFDBRLFRBLFRFFDDLUFULRDUDFLUBFRLULBRBDBBBDUDB",
    "U2 F2 D' F' L' F' B' U B' R' L2 B' U' F2 L2 D L2 U' F2 U2 L2 U2 ",
    "X BDX BDX BPX FP LP BPFP X B X FP RPLD FP X FP X FD LDY L X BD RP X BD RDY LDY LD "),

    ("BBURULRUULFLBRRBFBDFBFFDFRDUULUDRDDUDBFLLDFBRFLRDBURLL",
    "U F D L2 U2 R' L U2 B2 R B' D' R2 D' F2 B2 D F2 D L2 D2 ",
    "X B X B X B LD FD RPL FDX BD R BPX FP RD FP X BDFDX B X FDX F LD FD "),

    ("LBLLUBUFUBRUURFDLRRLRDFLDFLFRBRDDLBDFBFRLFFDRBUDUBUBDU",
    "U L' D2 B U B D2 F R B U2 R' D' R2 U L2 D R2 D2 R2 D2 F2 ",
    "X B LP FDX FX FX B X FDX B R FX FD RP BP RD F LD B RD BD RD BDX FD "),

    ("FUFBUBURDFLRDRFBUFLDRFFLBDDDBLFDLURLLUBFLURDRURULBRDBB",
    "B' R L F U' B' U L U R' B U L2 U2 L2 F2 U' F2 L2 B2 U2 ",
    "BP RL FX BPX FP X F L F RP X B X B LD BD LDY RD BP RDY RDY RD BD "),

    ("RURFUDDDFLBBFRULUBFFUDFLDLDRBFBDLBDLFRRULRDRBURUBBFULL",
    "U' D' R B2 U R2 F2 R' F' L' U' F2 B2 R2 D B2 U2 R2 U2 R2 ",
    "X BPFP RY LD B X FD RD FP RP BPX FP RDLDY RD B X BDX BD RD BD RD "),

    ("DBRDULBFBUDUDRRULLDRLLFRLBRFUBUDUDDFBFRBLFRFDFLLUBRUBF",
    "L' U R2 L F2 D2 B' U' L U2 R2 U D' R2 D' F2 R2 F2 ",
    "LPY RY RLD FDX BDX FP X BP R BD LD BFP LD FP X FD LD FD "),

    ("URBLUBFDUBRRLRFLULRLRBFFLDDBFFLDRFFBRBDBLUUUUDDFRBDDUL",
    "U' R L' F' R' U B R2 U B2 R' F2 R2 B2 U2 D R2 U D2 F2 U2 ",
    "X BP RLPY RP X FP X F L X BDX B LDY LPY LDY RDY LD BDFX FDX BDF RD FD "),

    ("BUULURRDFRURFRBUFUBLDDFLFBFDRRBDRUULLBDRLFBULBFDDBDFLL",
    "R D L' U' R2 B' L2 B2 U F' D' R U2 D' F2 R2 F2 D' F2 U L2 D ",
    "RY L X BP RP FDX FP X FDX BD R FP LPY L X BPFDX BD LD BDX FP X FDX F RD B "),

    ("FURBUDLRRUBDFRLBDFBUBFFRUDDRRLDDFULLRUUBLULLFBLDBBRDFF",
    "R B' U' F' B2 L2 D2 R' U2 F' L D L2 U2 D' F2 L2 U R2 B2 R2 ",
    "R BPX BPX BPFD LDY RDY LPY RD BPX F L FD RDLPY LD FDX FX FD RD FD "),

    ("LLRDUBUBBURBBRBLRRRLLLFUBFDDRFFDUULFDFFDLULURUDBDBRDFF",
    "R2 L2 U' B' U2 L' B' R L' D2 B D F2 B2 L2 U' F2 D B2 U ",
    "RDLDY RP BP RDY RP BP RPL X BDX FX FX BDFD RDY LP FD R BD L "),

    ("FDRUUBBBLDRBDRLFFFDUBLFRBURURUFDRFFUDLRFLBDLLUBLDBDLUR",
    "U D2 B' U' L' U' F U' B R' D2 L D' B2 U2 R2 D R2 L2 B2 ",
    "X BFD X FP X FP LP FP X FX BPX F RP X BD L BPX BDX BD RD F RDLDY LD "),

    ("FBBDULLFRUBRLRLDFUDRBBFFUURLLFUDDDBLURBFLRFRBDURDBUFDL",
    "U R' D L' U2 D L U2 L' D2 F' R D' L2 U2 R2 D' F2 R2 D' F2 D2 ",
    "X B RP F LP BDF L BD LP FDX BP RY RP X BD LD FD RP X FDX BD RP X BD RD "),

    ("LLBDURRDURBDLRLRULBBFBFDDBBFUUFDRLFFBRDFLLDDRLUUFBRUUF",
    "U2 L' U2 B' R L2 U R' F2 R' B D R2 U2 D R2 F2 D R2 L2 F2 ",
    "X BD LP BDX FP RLDY L X FP X FDX BPX F RY LDY RDL X BDX FD L X BDFDX BD "),

    ("LFFDUBLRDLLDURLBDFDUFLFFFDUUBRRDRDBUBLBRLUBBRRDUFBFLUR",
    "D2 B2 L' F R' L' B' L2 F2 D' R' U2 B2 D2 B2 D L2 U F2 D' F2 ",
    "X FDX FD LP B RPLP FP LD BDX BP RP FDX BDX FDX FDX B LD FX FDX FP X BD "),

    ("FBUDUBBRBUURLRRUFLDBLLFDRFFDLRFDRFUBDBRRLUUDFBLLUBDDFL",
    "R2 U R F' U R2 D2 B' R' B' R' U2 F2 D F2 U F2 D2 L2 B2 D' ",
    "RDY RY L FP X F LD BDX FP LP FP LPY RD BD L BD R BD LDY LD FDX BP "),

    ("ULBFURBDBDDDFRRBFFUBRLFUFRURBRUDDDLURRLLLFFBDLDFUBULBL",
    "F2 L U' R' B2 L' D B2 L B' D' B2 U B2 L2 U B2 L2 D2 R2 ",
    "FD L X BP RP X FD LPY R FDX B X BP RP BD L BDX FD L X FDX BD RD FD "),

    ("DUBBUFLFFLRLDRBBLRDUUDFLLRRFBDDDURRUFLBFLRBFDUBRDBLFUU",
    "D' F' D' L' F2 D F D2 R' L2 D2 R2 D B2 D B2 L2 U R2 ",
    "X FP X BPX BP LPY LD B L BDX BDFP X FDX BDX B RD B RDY RD F LD "),

    ("BRDFUUUUULBFDRDDDFRLBUFRLBBUDRFDLBLDRRFBLFDLFLUUFBRRBL",
    "L' U R' F B2 D F R B R L2 D R2 U2 F2 R2 B2 R2 U R2 ",
    "LPY RY LP BDFX B X B L F RDL X F LD BDX FD LD BD LDY L X BD "),

    ("DBRLUFFUBDLFBRFLBLLFRFFUBLBRUDDDDFUULDUBLRRRUDLFDBRBRU",
    "R2 B2 R' L' F2 R2 B' D L U B D B2 R2 D' R2 D B2 D2 F2 ",
    "RD BD RPLP FD RD BPX F L B X FX B X BD RDY LPY LDY R BD RD FD "),

    ("LLURULDUDLBLURBBRFRFFRFLFRURBRFDDBBRDFBFLULDDFDBUBLUDU",
    "U F D' R' B' U R' F' D' F U2 L B2 U2 D L2 F2 L2 U F2 L2 U ",
    "X B X B X BP RP X BPX B RP X BPX BPX FX BD L X FDX BFD LDY LDY RD FX BD RDY R "),

    ("UFLRULBLUBUBBRFRDFDFRBFLFUFLRDDDRBBLRFRBLULLUDDFUBDDRU",
    "U R L' D2 B' L F2 U F L2 U2 L D' R2 D2 R2 B2 U' L2 F2 D' L2 ",
    "X B RLP FDX FP L BDX FX F LDY RDY RY RP X BD RD BDX FD LPY RD BDX FP RD "),

    ("BRRLUFBFFLRFDRUDLURDUFFRULFRDLRDUDBBLFULLUBUFDBDBBBLDR",
    "U' D' F D' B' L2 F' R D' F B R2 F2 R2 D' R2 F2 U2 D R2 F2 ",
    "X BPFP X B X BPX BP LD FP RY LP BF X FDX BDX BD LP BDX FD RDL X FDX BD "),

    ("DRDUUBRRLBLLRRLUFDUFULFBFDLULFDDUDBBFRBDLUFFRBDRFBBRUL",
    "L' B R D' L B R D' F2 U2 F L2 F2 U B2 D F2 R2 D' B2 D2 ",
    "LP B RY LPY R B L X BPX BDX BDX F RD FDX FX FDX FX FD LDY RP BD RD "),

    ("LLFLUBRURDLUFRDRURUBFRFULBDDRBRDRLDUBUBDLDDFBLFUBBFFLF",
    "L B' R' U' F L U D2 B' R B2 R2 F2 D2 B2 U2 D B2 L2 U2 ",
    "L BP RP X BPX B L X BDFX BP R BD RD FDX FDX FDX BFD X BD LDY RD "),

    ("LLBRUFUBBUURURDLLRBDLRFBBLFLUUDDFRRFFDRRLFUFDDBDLBBDUF",
    "F L' U D B' L' U' D R' U2 F' D2 R2 U2 L2 F2 U L2 B2 L2 U ",
    "F LPY RL BPX BP RPL FP RDY RP X BDX BDX BDX BD RDY L BDX BDX FD L "),

    ("FLLUUULLULBDRRFUFDUDBBFBBFRLRBBDURDBURFDLLFDDFURLBRRFD",
    "F2 B2 U2 B' U F2 D2 F B2 R F R2 U R2 D R2 L2 B2 U F2 D2 ",
    "BDFDX BDX FP X FX FDX FDX BFD R B RDY L X FD R BDFDX BD L FD RD "),

    ("FURFUDBUDFLBFRBDRDUBRBFRULBFFRBDULDFUULRLRBDLULRLBDLFD",
    "U R L D R B U D F2 B2 R' U L2 B2 R2 U F2 D R2 B2 U' ",
    "X B RL F RY L BF RDLDY LP B RDY RDY RD B X BDX B RDY RD FP "),

    ("BFFBUFUBFDRDDRDFRDBRLFFBBDUDLLBDUUFLUURLLLFLRRDLRBUBUR",
    "F' B' U2 R' F' B2 R' F2 L U' R U' B2 L2 D L2 D B2 D' F2 D ",
    "BPFP X BD RP X BPFD RP BD L X FP R FP X BD LDY L X BD L X FD LP BD L "),

    ("UFFDUULUUBFRLRFLDUDLRRFBBRDDUFDDFFBLLLBRLDDBRURBLBBFUR",
    "U D' F' R2 L' B2 R' L' D' L2 F' D' L2 U2 R2 F2 D' R2 F2 D' ",
    "X BFP X BP RDLP FD RPLP X BP LDY LP BPX BDX BDX BD LDY RP BDX BD RP "),

    ("DDRBUUBUFUBFURLBRFDFRRFRFFULLRDDBLULBDRLLFUFUDRLDBBDLB",
    "U' R' B2 R F' R U2 D F2 U2 R' U' R2 U R2 D' B2 L2 F2 D2 ",
    "X BP RP X FD R BP RY RLD BD LDY LPY RP X BD R BD LPY RD FD LDY RD "),

    ("BDRLUBDBDFRBFRRBFFRURRFUDDDLLLUDLFDUUUBBLFRRFUBLDBLLFU",
    "R2 F D L' D B U' L' D2 R' B' R2 D R2 F2 U' R2 D' F2 U' ",
    "RD FX F LP FX FX FP LP BD RP X BP RDY L X FDX BD RP X BD LPY LDY LP "),

    ("RFLUUFFDFDRBLRBRBRULLBFFUUFFFDLDDUDDURRBLRBULDDBLBUBRL",
    "F2 L B2 U2 B' L' D R' U R' F2 U F2 B2 R2 D' F2 B2 U' F2 ",
    "FD L BDX BDX FP LPY RY LPY RY RP BDX FX BDFD RDY LP BDFD RP FD "),

    ("DURFULUBUFDFLRFRUBLRLRFBFDBUBUFDRDFRBRBULDFLRDLLDBBDUL",
    "U L B2 R2 D' R B D2 F R L F R2 D R2 B2 D2 F2 U' D2 L2 B2 ",
    "X B L X FD RDY RP X FX B RD FX BF X B X FD R FDX BD RD FD RDLPY LD BD "),

    ("BRDFUBUBULULRRUDFUFRBDFUDFFRDLDDLFLFRULLLRDBBBFULBBRDR",
    "F2 R D L B2 U L2 B' R' U D' F' R2 F2 R2 D F2 U2 D B2 R2 U' ",
    "FD RY L X B X FD RY LD FP RP X BPFX FP RD FD RDY L FD RDL BDX FD RP "),

    ("LFDLUUDRDBBBRRUBFLFFLBFURDUFBRUDDUBFFDRRLLBLURLDFBDURL",
    "D' R B L' D R' D2 R F B L' U' R2 U' F2 L2 U' L2 D R2 U2 ",
    "X FP RY L X BPX B X BPX FDX F RL BPX FP X BDX BP RDY RD BP RD F LD BD "),

    ("FUDLUBDLFLRBURFUDLLDUFFLBUFURRBDFRDBRFFDLRBLLRBDUBRDBU",
    "F' U D2 B2 L B' U' R2 F2 R' D' L2 U' B2 L2 D' R2 L2 B2 D ",
    "FP X BFD X FD L FP X FP RDY LDY LP BP RD FP X FD RDY LPY RDLD FDX B "),

    ("LUFFUURDFDLURRDBBFUBLUFFBRDDDLLDRRLDBLBBLRUDRLFUFBURBF",
    "L F' L2 F D2 R2 L2 B2 U' F U D R2 D' B2 L2 F2 R2 U2 D' ",
    "L FP LD FX FD RDLDY LD BP R BF X FDX BP LDY LDY LDY LD BPFD "),

    ("URDBUDLLBDFLBRUDLFBDRBFDDURLLFRDBULRBUUDLRLUFBFRFBRUFF",
    "B2 U2 L' B' R L2 F B R2 L F' U' B2 U B2 R2 U' R2 F2 B2 L2 ",
    "BDX BD LPY LPY RDL X BF RLD FP X FP X FDX B X BD LDY LPY RD BDFD LD "),

    ("RLFDUFFBLDUDBRLDFFLDBUFULLBBDRRDDFURURURLLLBURFBBBFURD",
    "U F' R2 F2 U' R F R2 D F2 R' F' D B2 U2 R2 B2 U2 R2 D F2 R2 ",
    "X B X BP RD BDX FP RY L X FDX F LDY RP X BPX B X BDX BD RDY LD BDX FDX B RDY RD "),

    ("BRDBUFBFBUURBRRFUUDLLDFDDDRLFULDLBULRURLLRDBFFFUBBDFRL",
    "F' D B2 R' L2 U2 B L' F' D L' U R2 U' L2 B2 D2 B2 D2 L2 B2 ",
    "FP X FX FD RPLD X FDX B LP FP X F LP B RD BP LDY LD FD LD FDX BD LD "),

    ("BRBFUURBFRRDURLBDDFRDFFBBLRUDDLDRUBFRUUFLDLULLFUBBLLDF",
    "U F' B R' D B' R U R' F U' L U' B2 U2 L2 U' R2 B2 L2 U F2 ",
    "X B X BPF RP X B X BP RY RY LP FX FP R FP X FDX BD RD BP LDY RDY LD B X BD "),

    ("FLDRUBBRUBDRBRRLRFDFRDFUUUBFFDDDUULRDDRLLFBLLFULBBFUBL",
    "U R F' U' L' F R2 F R' U2 B L' F2 B2 U F2 L2 D L2 D R2 U2 ",
    "X B RY RP BPX BP R FD R FP X FD L X FP RDLDY RY LD FDX B X BDX FX BDX FD "),

    ("BFRLURUFFLFBBRRDLDLLUDFRULFRDLFDURBRLBBRLBDUFUDDDBUFUB",
    "R B' D' L' U R D L' D R2 F D2 F2 D' R2 L2 B2 R2 U' R2 ",
    "R BPX FP LP B R F LP F RDY R FD RD FP X BDFD LD FDX FP X BD "),

    ("BDFBUUFDLUFDLRUFURDBFLFDUURLBUDDRDLBDRLFLFLRBRFRLBRUBB",
    "R L2 U F R2 D2 R' L2 U F' D' L' U' B2 U' L2 U F2 R2 D2 L2 D ",
    "RLDY R FX FD LD BDFP RY RP X BPX FP X BP LD BPX BDX F RDY RD BD LD B "),

    ("FDLBUBRLUBUFDRURRBDURFFLLDUDFFRDFDLLDLFRLUBBBUBLRBDUFR",
    "U R D' R U' B2 D2 R' B' D' F' L' U L2 D' F2 L2 D F2 U2 L2 U ",
    "X B R FP R BPX FDX BD RP X BPX FP X BP LPY L X BD RP X FDX FD RY RDY RD FD R "),

    ("BBFRURDDLBFRDRFDLDFLUDFRFDFLBLUDBRULDURULFBLUURRLBFBBU",
    "U' F' D2 B' L' U2 R2 D R D2 R' F2 U L2 F2 D B2 D2 L2 D' R2 ",
    "X BPX BPX BDX BP LPY RDY LDY RY RY LDY LP FDX F RDY RD B LD BDX FDX FP X FD "),

    ("BDBBULRBRFBLLRDFFBURUDFUDUULFLUDRRFDDUBLLRFRFUBRLBFLDD",
    "U B' L' B L F B D' R L' F R U L2 F2 B2 D F2 D2 R2 U D2 ",
    "X B X FP LP F L BF X BP RLPY L X FX B X FD RDLDY RY RDY LD BD RLD "),

    ("URLBULDDULDBBRLRRFRRBFFLFLFDFDUDUURRBUBBLDLFLDFRUBDUBF",
    "U L2 U D2 R' D B2 L F D L2 B' R2 B2 D2 F2 U2 L2 F2 L2 U L2 ",
    "X B LD BFD RP FX FD L B X B LDY RP X FD RDY LDY RDY LD BDX FDX FD L FD "),

    ("LDUFULFRURDRLRULBDDFFRFBFBURDBBDUBFLULLDLURRDBFFLBRBUD",
    "F' U2 D' F U' F2 U' F D B' L' D2 F2 U R2 U' L2 B2 U' B2 U2 ",
    "FP X BDFP X B X FP X FDX BPX B X B X BP LPY LD FD RY LDY LPY LD BDX BPX FDX FD "),

    ("FDBBUDUBRDBLLRFBRRBUFRFULDDUFLFDURLUDRRLLDDUFULLRBFFBB",
    "R2 F' R L' U R' U2 F' D2 F R U' R2 U L2 U' B2 L2 U2 D B2 ",
    "RD FP RLPY RY LPY LD FP RD FX B LP BD L FD LPY LD FDX BDF LD "),

    ("UFBBURLLBRFDBRRFURBDUDFLDBDLDRFDLUBDRUUFLRLDFLLFUBUBRF",
    "R D F' L F' L2 B' U' D' R D B' U2 F2 U' L2 B2 U' L2 D R2 L2 ",
    "RY L FP X B X BPX FDX BP RPLP X F L X FP RD BD RP X FDX BD RP X BD L BDFD "),

    ("DURBULRULBUDRRRLDLDBULFFFBBULDDDRBBFLDFDLFUFRBFFUBLURR",
    "F U' R F' R L D2 L' B' D R F2 U' R2 B2 D R2 D2 R2 L2 B2 ",
    "FX BP RY RP X BF X BDX FP LPY L B X FD RP X FDX FD L X BD LD BDFDX BD "),

    ("UFBLURRDLDURRRLUFFFBBFFDULRFFBRDUFBDLBUDLRLBLDDBUBLRUD",
    "B U R' D2 R2 D' B2 U' R B' U R2 D2 R2 B2 U F2 D' B2 U' ",
    "B X B RP FD RD FP X FDX FP RY RP FX FDX FDX BD RDY L X BD RP FD LP "),

    ("FLBUUDFBDBFURRRUBLLULRFFLLFBDRBDLDRDRLUFLDBDURFDBBUFUR",
    "U' D' R' F' R2 U' D2 F U' L U R2 U2 L2 F2 R2 L2 U' F2 D' ",
    "X BPFP RP X BP RDY RDLP B LPY RY RY RDY LDY RD BD RDLDY RP BD LP "),

    ("DRLUUBFBRBLURRLRUBLRDDFDLFUFUFFDBRDUBRUFLLFDDBFLUBLRBD",
    "D2 R' D' F2 B D R2 D2 R' F2 D' F2 U' B2 L2 U2 D R2 U ",
    "X FD RP FP X BDFX B RD BD RP X FDX FP X BDX FP X BD LDY RDL X FD R "),
]

if __name__ == '__main__':

    cmd = './solve'

    if len(sys.argv) > 1:
        fname = sys.argv[1]
        logging.info('loading tests from %s', fname)
        with open(fname) as f:
            cnt = 0
            t = f.readline()
            while t:
                logging.info('running test %d...' % (cnt + 1))
                t = t.strip()
                r = f.readline().strip()
                res = subprocess.check_output([cmd, t], stderr=open(os.devnull, 'wb')).strip()
                if res != r:
                    logging.error('Error for %s:\n\tmust be: %s\n\tgot: %s' % (t, `r`, `res`))
                    sys.exit(1)
                cnt += 1
                t = f.readline()
            logging.info('all %d tests passed' % cnt)
    else:
        for i, tst in enumerate(javares):
            logging.info('running test %d of %d...' % (i + 1, len(javares)))
            t, r, m = tst

            res = subprocess.check_output([cmd, t], stderr=open(os.devnull, 'wb')).strip()
            if res != r.strip():
                logging.error('Error for %s:\n\tmust be: %s\n\tgot: %s' % (t, `r`, `res`))
                sys.exit(1)

            res = ' '.join([o.name for o in convert_moves.convert_moves(res.split())])
            if res != m.strip():
                logging.error('Error for %s:\n\tmust be:\t %s\n\tgot:\t\t %s' % (t, `m`, `res`))
                sys.exit(1)
        logging.info('all %d tests passed' % len(javares))

"""
print '("' + t + '",'
print '"' + r + '",'
print '"' + subprocess.check_output(['python','convert_moves.py', t], stderr=open(os.devnull, 'wb')).strip(), '"),\n' 
"""
